### ISSUE TITLE
Need a release

### ISSUE THREAD

**Issue by andrewdavidsmith** [smithlabcode/smithlab_cpp#12]
Do we need a tagged release of smithlab_cpp so that we can move to C++11 and have a release that we know works with older compilers? Or should we just record a commit or something?

**Comment by bdecato** [comment]
Does anyone outside our lab develop using smithlab_cpp?

I think we can just move up to C++11 (or 14) in smithlab_cpp, and when we update the submodule associated with a specific set of software (preseq, methpipe, whatever), the next tagged release of that software should note the upgrade.

**Comment by bdecato** [comment]
Bumping this.  We need to talk about C++11 integration, particularly in replacing the RNG class.  We will tag and include a C++11 flag in all Makefiles in the next release of methpipe.
