### ISSUE TITLE
Incompatibility with gcc 5+

### ISSUE THREAD

**Issue by timydaley** [smithlabcode/smithlab_cpp#13]
Hi guys,
I have someone who has an issue with installing preseq with gcc 5.2 that should affect all of our software.  gcc 5+ does not let copy-on-write of std::string and requires that std::list know their size (see https://meetingcpp.com/index.php/br/items/the-c-highlights-and-more-of-gcc-51.html and http://stackoverflow.com/questions/34571583/understanding-gcc-5s-glibcxx-use-cxx11-abi-or-the-new-abi).  I'm only having problems with the former.  
The solution is easy, tell gcc to use the old definitions.  Before I edited everything, I wanted to make sure this is cool.
Thanks.

**Comment by andrewdavidsmith** [comment]
Show us proposed changes first. This might not be something we can approve quickly.

**Comment by timydaley** [comment]
From http://stackoverflow.com/questions/34571583/understanding-gcc-5s-glibcxx-use-cxx11-abi-or-the-new-abi : 
Defining the following macro before including any standard library headers should fix your problem: #define _GLIBCXX_USE_CXX11_ABI 0

**Comment by andrewdavidsmith** [comment]
We are only interested in good fixes that will become part of our code base. This seems like "a" fix, but I'm not convinced this is the best way to fix any particular problem. I am also not convinced of how widespread is this problem.

**Comment by andrewdavidsmith** [comment]
We now do not support anything earlier than GCC 5.3, and possibly there are some systems on which GCC 5.3 does not have all the c++11 that we use.
