### ISSUE TITLE
Adding robustness in OptionParser for specifying options more than once

### ISSUE THREAD

**Issue by andrewdavidsmith** [smithlabcode/smithlab_cpp#14]
This can be problematic, when there is no intention by the user or developer for this to work. I had a case where the terminal was not printing what I was typing (remote, connection issues) and I had specified arguments multiple times unintentionally.

**Comment by bdecato** [comment]
What's the correct behavior: error message that says "duplicate options detected?"

What if the option is or is not discordant, i.e. -e somefile ... -e differentfile vs -e somefile ... -e somefile?  Should we only throw the error message on discordant duplicates and run on non-discordant duplicates?

**Comment by andrewdavidsmith** [comment]
I’m not sure the words “discordant” or “concordant” have any meaning in the context of this code. It seems you are talking about creating new functionality.

**Comment by andrewdavidsmith** [comment]
Right now we allow for duplicates if the option is a Boolean flag. Otherwise we report the duplicate by throwing an exception.
