### ISSUE TITLE
Should SAM support be here?

### ISSUE THREAD

**Issue by andrewdavidsmith** [smithlabcode/smithlab_cpp#15]
We have a SAM.hpp and SAM.cpp file, presumably for some wrapper, but when I try to build the code it complains about no sam.h. Is this intended behavior?

**Comment by mengzhou** [comment]
It requires header files in `methpipe/src/samtools`.

**Comment by andrewdavidsmith** [comment]
So smithlab_cpp requires stuff in some totally separate project?

**Comment by mengzhou** [comment]
I will move it to `methpipe/common`

**Comment by mengzhou** [comment]
Wait a sec, so `preseq` also has this program called `bam2mr` which also uses `SAM.hpp` and `samtools`. But it seems it's basically the same as `to-mr` in `methpipe`.

**Comment by andrewdavidsmith** [comment]
Maybe I'll just add something in the Makefile to allow a set of files that should be ignored when compiling. It seems strange to have these dependencies in the wrong directions (and in two wrong directions).

**Comment by KochTobi** [comment]
Hi there, I still have an issue with a missing `sam.h` file.
### Issue description
When compiling `preseq` which uses `smithlab_cpp` as a submodule the compilation failes with

```
make all SAMTOOLS_DIR=/mysamtoolsdir/
...

In file included from load_data_for_complexity.cpp:183:0:
/<mydir>/preseq/smithlab_cpp/SAM.hpp:28:17: fatal error: sam.h
   : No such file or directory
 #include "sam.h"
                 ^
compilation terminated.
make: *** [load_data_for_complexity.o] Error 1
```

### Expected behaviour
The program compiles and produces executables.

### How to reproduce
1) clone the git repository using 
`git clone --recurse-submodules https://github.com/smithlabcode/preseq.git`
2) switch to desired version 
`cd preseq`
`git checkout v2.0.3`
3) execute make all
`make all SAMTOOLS_DIR=/<mysamtoolsdir>/`

**Comment by timydaley** [comment]
Hi KochTobi,
Can you verify that you have the sam.h file?  Type find /<mysamtoolsdir>/ -name "sam.h"  Some versions of samtools don't have the API.  Alternatively you can use the samtools API that we have forked in preseq.

**Comment by KochTobi** [comment]
Indeed I do not have the `sam.h` header file. When I use the provided version of samtools (which is `0.1.16beta` as far as I can tell) I am missing some 'gsl' files.
'''
moment_sequence.cpp:21:30: fatal error: gsl/gsl_sf_gamma.h
   : No such file or directory
 #include <gsl/gsl_sf_gamma.h>
                              ^
compilation terminated.
'''
Do I need to copy gsl `source` files to the preseq `source` directory? 
I have installed the gsl libs on the system.

**Comment by timydaley** [comment]
No, gsl is general computing library.  If you're on a Linux system, gsl should be automatically included.  If you're on a Mac, gsl should be included in Xcode.  If you're on Windows, .... well, I don't know anything about Windows.

**Comment by andrewdavidsmith** [comment]
@KochTobi This is an issue I opened, and has nothing to do with preseq. I'm going to close it, and ask that if you have a question about preseq, can you ask it in a location related to preseq? We will be happy to help get preseq working for you.
