### ISSUE TITLE
Chromosome read but not stored

### ISSUE THREAD

**Issue by mengzhou** [smithlabcode/smithlab_cpp#16]
https://github.com/smithlabcode/smithlab_cpp/blob/master/smithlab_os.cpp#L127-L144

This function is used by a number of programs. Individual programs will call this function to read through FASTA files, but nothing is stored, so they will load data again in some other function.

**Comment by andrewdavidsmith** [comment]
Seems the code has changed too much since this issue was opened for the link to be meaningful, so need to close.
