### ISSUE TITLE
Our tools need to take zipped files as input

### ISSUE THREAD

**Issue by bdecato** [smithlabcode/smithlab_cpp#22]
Data files for WGBS are starting to get ridiculously large. For example, the latest paper on embryonic reprogramming in mouse has a total of 668GB in SRA files, before dumping to FASTQ.

We should add functions in smithlab_cpp that allow .gz and .bz2 extension files to be read in to our tools with no issues, and utilize these functions in repositories like `methpipe` and `walt`.

**Comment by bdecato** [comment]
After researching this issue for awhile and discussing with @andrewdavidsmith, it seems the simplest way to provide this kind of functionality for ourselves and our users is to just explain how to pipe input in the manual. Reading from `stdin` is already supported by the vast majority of our programs, so updating the manual to include a tutorial to `bzcat <compressed_file> | methcounts` might keep us the most flexible and helpful.

Using zlib or boost libraries introduces another dependency in our code, which could be remedied slightly by including precompiled binaries in our releases, but would not be ideal. Using a system call to `bzcat` or `zcat` would rely on the success of such a call, and would limit the types of compression a user can have to those two algorithms.

One other solution @saketkc brought up was specific to FASTQ files and is Heng Li's header file for reading zipped fastqs. It may be an option for WALT, hasn't been changed in years, and is a single file we could add to our repo. That said, it is specific to gzip. (https://github.com/lh3/readfq).

**Comment by mengzhou** [comment]
I'm not sure if pipe works for all our programs. Remember the functions for file format detection? They need to open the file and read the first data line to determine the format. And I remember there was a user who used `to-mr` with pipe but it returned some error.

**Comment by andrewdavidsmith** [comment]
We could write a function that detects format using a stream, and then rewind the stream. But that might cause problems when the stream is not associated with a seekable file. We might need to wrap the stream so that we could remember the portion used to determine the format, which would allow us to avoid rewinding. We can test whether the file is seekable using lseek or something...

**Comment by andrewdavidsmith** [comment]
For objects that have templated `operator>>` based on `getline` for `std::istream` these same extraction operators can be used with the `igzfsream` from `zlib_wrapper.*pp` and require linking with `-lz` so `zlib` must be installed.
