### ISSUE TITLE
OptionParser needs a way to check if the same option is specified twice on the command line

### ISSUE THREAD

**Issue by andrewdavidsmith** [smithlabcode/smithlab_cpp#25]
Right now if an option is specified more than once, the final appearance is used. There should be some kind of error reported.

**Comment by guilhermesena1** [comment]
I have modified it so it throws a runtime error if any argument that is not boolean is assigned twice

So for instance if you have

```
    OptionParser op(argv[0], "","");
    string outfile="chimichanga";
    bool verbose;
    op.add_opt("output", 'o', "output name", false, outfile);
    op.add_opt("verbose", 'v', "verbose", false, verbose);
```

The following are *allowed*:
```
./program -o somefile.txt -v -v -v -v -v 
./program -output somefile.txt
./program -o -output somefile.txt # outfile will get the value of "-output" and "somefile.txt" will be ignored. Maybe add an issue to check if following argument starts with a dash? -
./program -v
```
The following are *not alowed*:
```
./program -o outfile.txt -o otheroutfile.txt
./program -o outfile.txt -output outfile.txt
./program -o outfile.txt -output
```

**Comment by guilhermesena1** [comment]
367e59b10fa8c2d211d231783119c95ea21d6a3b

I have modified it so it throws a runtime error if any argument that is not boolean is assigned twice

So for instance if you have

```
OptionParser op(argv[0], "","");
string outfile="something";
bool verbose;
op.add_opt("output", 'o', "output name", false, outfile);
op.add_opt("verbose", 'v', "verbose", false, verbose);
```

The following are *allowed*:
```
./program -o somefile.txt -v -v -v -v -v 
./program -output somefile.txt
./program -o -output somefile.txt # outfile will get the value of "-output" and "somefile.txt" will be ignored. Maybe add an issue to check if following argument starts with a dash? -
./program -v
```
The following are *not alowed*:
```
./program -o outfile.txt -o otheroutfile.txt
./program -o outfile.txt -output outfile.txt
./program -o outfile.txt -output
```

**Comment by guilhermesena1** [comment]
up!

**Comment by andrewdavidsmith** [comment]
I think we need to have a hash function for options and a hash table in which to store them.

**Comment by guilhermesena1** [comment]
this is useful if we want to store multiple values for the same flag (like how many -v s were passed). This specific issue could be solved in a simpler way, just check if the "specified" flag is already true, in which case the argument was already passed previously.

**Comment by andrewdavidsmith** [comment]
I think we are going to have to remove this functionality. Some of the boolean flags are being used to negate variables, and others are being counted. I think we can remove the counting functionality and require, e.g., different flags for different degrees of verbosity.
