### ISSUE TITLE
ProgressBar: Document magic numbers and ensure unsigned evaluated as positive

### ISSUE THREAD

**Issue by andrewdavidsmith** [smithlabcode/smithlab_cpp#27]
The ProgrssBar class constructors have the following:
```
    bar_width = max_bar_width - message.length() - 3 - 5;
```
With no explanation. This needs to be documented, and likely some check done somewhere to ensure the `bar_width` is valid. Similar for: `total(x-1)`.

**Comment by masarunakajima** [comment]
This issue was addressed in commit https://github.com/smithlabcode/smithlab_cpp/commit/d969b002e7322f8b79539e08fce312d1dd78da86
