### ISSUE TITLE
ProgressBar: Incorrect order of initialization in constructor

### ISSUE THREAD

**Issue by andrewdavidsmith** [smithlabcode/smithlab_cpp#28]
When initializing member variables directly in the constructor with notation like:
```
  ProgressBar(const int start_, const int finish_,
	      const std::string message = "completion") :
    start(start_), finish(finish_), total(abs(finish - start)-1),
```
make sure the order of variables is correct. Right now it is not for ProgressBar (in the above code).

**Comment by masarunakajima** [comment]
@andrewdavidsmith , could you elaborate on what exactly is not in order? It seems fine to me.

**Comment by masarunakajima** [comment]
addressed in https://github.com/smithlabcode/smithlab_cpp/commit/13d30c96595c992bd44b4397ce44bd9d26d4f02d
