### ISSUE TITLE
Formatting "about" message in OptionParser

### ISSUE THREAD

**Issue by andrewdavidsmith** [smithlabcode/smithlab_cpp#29]
Currently the lines are getting too long. It's because the line length is calculated without including the whitespace between words. This is a fix that will require just modifying a couple lines of code. The line length needs to have a "+1" for every space added between the words.

**Comment by guilhermesena1** [comment]
Just confirming, is it just changing
```  
line_len += parts[i].size();
```
to
```
  line_len += parts[i].size() + 1;
```
on line 213 of OptionParser.cpp?

**Comment by guilhermesena1** [comment]
e140779fe3c6567edf731d6237ba22c9b3c4162f
