### ISSUE TITLE
Boolean flags get unset when they appear an even number of times on the command line

### ISSUE THREAD

**Issue by andrewdavidsmith** [smithlabcode/smithlab_cpp#9]
Boolean flags get unset when they appear an even number of times on the command line.

This is a problem. If you put "-v" twice it will be like having it 0 times.

**Comment by mengzhou** [comment]
is this a bug of optparser?

Best regards,
Meng

**Comment by andrewdavidsmith** [comment]
It's a bug in OptionParser.hpp. Sorry. I didn't realize it would associate the issue only with the repo and not the file I was looking at.
